AWSTemplateFormatVersion: '2010-09-09'
Description: MediaWiki upload files
Parameters:
  DomainName:
    Type: String
    Description: Domain name
  CertificateArn:
    Type: String
    Description: Certificate ARN
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Bucket"
  Oac:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName} origin access control"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior: 
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: S3
          ViewerProtocolPolicy: allow-all
        Enabled: true
        IPV6Enabled: true
        Aliases:
          - !Ref DomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins: 
          - DomainName: !GetAtt Bucket.RegionalDomainName
            Id: S3
            OriginAccessControlId: !GetAtt Oac.Id
            S3OriginConfig: 
              OriginAccessIdentity: ''
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Distribution"
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref Bucket
      PolicyDocument: 
        Version: "2008-10-17"
        Statement:
          - Principal: 
              Service: 
                - "cloudfront.amazonaws.com"
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource: 
              - !GetAtt Bucket.Arn
              - !Sub "${Bucket.Arn}/*"
            Condition: 
              StringEquals:
                AWS:SourceArn: 
                  - !Join
                    - ':'
                    - - 'arn:aws:cloudfront:'
                      - !Ref AWS::AccountId
                      - !Join
                        - '/'
                        - - distribution
                          - !Ref Distribution
